### PR TITLE
Prevent marker-only changes from producing phantom diffs

### LINKED ISSUE #7349: ChangeDependencyGroupIdAndArtifactId generates empty diffs on Java files after #7202
## What happened

- After merging #7202 (Expand star imports in ChangePackage), `ChangeDependencyGroupIdAndArtifactId` now updates `JavaSourceSet` markers on Java source files in its `getVisitor()` phase. This causes the test framework to detect "empty diff" errors in downstream repos where tests don't provide explicit `after` text for Java source files.

The error: `AssertionError: An empty diff was generated. The recipe incorrectly changed a reference without changing its contents.`

## Affected downstream repos

All started failing on April 11, 2026 (were green on April 10):

- **openrewrite/rewrite-hibernate** — `MigrateToHibernate61Test.groupIdHibernateOrmRenamed()`
- **openrewrite/rewrite-migrate-java** — `AddCommonAnnotationsDependenciesTest.changeAndUpgradeDependencyIfAnnotationJsr250Present()`
- **moderneinc/rewrite-dropwizard** — `MigrateDropwizardToSpringBoot3Test.addsSpringStarterJdbcWhenDropwizardDbIsUsed()`

## Root cause

`ChangeDependencyGroupIdAndArtifactId.getVisitor()` now processes Java files (line 350-351) and calls `updateJavaSourceSet()`, which modifies the `JavaSourceSet` marker via `JavaSourceSet.updateOnSourceFile()`. This returns a new `SourceFile` object (different identity), causing the recipe framework to generate a `Result`. However, the printed text is unchanged — only markers differ — so `RewriteTest` flags it as an "empty diff" error.

The PR's own test (`updatesJavaSourceSetMarkerOnJavaFiles`) handles this by providing explicit `after` text identical to `before`. But downstream tests don't know about this new behavior.

## Suggested fix

Consider one of:

1. **Filter marker-only Results in `InMemoryLargeSourceSet.getChangeset()`** — use `Result.isLocalAndHasNoChanges()` to skip Results where text is unchanged. This would need adjustment to the `updatesJavaSourceSetMarkerOnJavaFiles` test (use `afterRecipe` validation instead of `after` text matching).

2. **Relax the "empty diff" check in `RewriteTest`** — instead of failing when a Result has no text change and no `after` spec, silently ignore the Result. This is a less invasive change but reduces bug detection coverage.

3. **Move marker updates out of the visitor phase** — apply JavaSourceSet updates through a mechanism that doesn't generate Results (e.g., execution context sharing, or a post-processing step).

## Workaround

Downstream repos can add explicit `after` text (identical to `before`) for Java source files in affected tests. PRs are being submitted for the affected repos.

### PR DESCRIPTION
**Pull request by steve-aom-elliott**
## Summary

- Dependency-modifying recipes now update `JavaSourceSet` markers (#7202), which can produce `Result` objects with identical before/after printed text. This caused "An empty diff was generated" test failures in downstream repos:

- moderneinc/rewrite-dropwizard — `addsSpringStarterJdbcWhenDropwizardDbIsUsed`
- openrewrite/rewrite-hibernate — `groupIdHibernateOrmRenamed`
- openrewrite/rewrite-migrate-java — `changeAndUpgradeDependencyIfAnnotationJsr250Present`
- openrewrite/rewrite-spring — `flywayStarterOmitsVersionWhenManagedByParent`

Three fixes, each addressing a different layer:

1. **`JavaSourceSet.addTypesForGav` idempotency** — returns `this` when the gavKey already exists with the same types, preventing unnecessary object allocation (especially for LSTs with empty `gavToTypes` maps where the existing guard in `changeDependency` doesn't fire).

2. **`JavaSourceSet.updateOnSourceFile` (cached overload)** — checks whether the source file's current marker is already the cached instance before calling `withMarkers`, preventing O(n) new tree references across all files in a source set when only the first file truly changed.

3. **`RewriteTest` safety net** — accepts marker-only changes (identical before/after text) instead of failing, since these represent legitimate internal state updates. Calls `afterRecipe` so marker assertions still work.

All four downstream test failures were verified to pass with these changes.

- Closes #7349

### CODE REVIEW

File: rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java [hunk 1]
```diff
@@ -66,6 +66,11 @@ public class JavaSourceSet implements SourceSet {
      * @return a new JavaSourceSet with the types added
      */
     public JavaSourceSet addTypesForGav(String gavKey, List<JavaType.FullyQualified> types) {
+        List<JavaType.FullyQualified> existing = gavToTypes.get(gavKey);
+        if (existing != null && existing.equals(types)) {
```
Comment (timtebeek) [inline rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java:70]: I suppose there's no way to prevent the deep equality comparison here? Are there any shortcuts like comparing the sizes? Or is that already built into equals?

Comment (timtebeek) [reply rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java:70]: Looks like the size check is [one of the first things it does](https://github.com/openjdk/jdk/blob/909d4e758c045a0d8cea52f6a1333839f7d6c43e/src/java.base/share/classes/java/util/ArrayList.java#L637), thankfully. Then this is less of a concern.

**Review by timtebeek — APPROVED** [review]
