### PR TITLE
RemoveObjectsIsNull fails on negated expressions fixed

### LINKED ISSUE #4244: org.openrewrite.java.RemoveObjectsIsNull fails on negated expressions
## What version of OpenRewrite are you using?

- org.openrewrite:rewrite-core:jar:8.27.4
- org.openrewrite.recipe:rewrite-migrate-java:jar:2.17.0

## What is the smallest, simplest way to reproduce the problem?

```java
import org.junit.jupiter.api.Test;
import org.openrewrite.java.JavaParser;
import org.openrewrite.java.RemoveObjectsIsNull;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.java.Assertions.java;

public class KnownBugsTest implements RewriteTest {

  @Override
  public void defaults(RecipeSpec spec) {
    spec.recipe(new RemoveObjectsIsNull()).parser(JavaParser.fromJavaVersion());
  }

  @Test
  public void negatedRemoveObjectsIsNull() {
    rewriteRun(
        java(
            """
            package com.helloworld;
            
            import java.util.Objects;

            class Hello {
              public boolean hello(String abc) {
                return !Objects.isNull(abc);
              }
            }
            """,
            // "!abc == null" is not a valid expression
            """
            package com.helloworld;

            class Hello {
              public boolean hello(String abc) {
                return abc != null;
              }
            }
            """));
  }
}
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Yes, possibly. Reporting this in the meantime.

### PR DESCRIPTION
**Pull request by Riyazul555**
## What's changed?
This version includes parentheses around the JavaTemplate expressions to ensure correct negation handling, and uses SimplifyBooleanExpressionVisitor to simplify expressions as needed.

## Any additional context
- Fixes #4244 

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by Riyazul555** [comment]
@timtebeek do checkout this also
Thanks

**Comment by timtebeek** [comment]
Thanks for getting this started @Riyazul555 ; I've added the test from https://github.com/openrewrite/rewrite/issues/4244 and the suggestion from https://github.com/openrewrite/rewrite/issues/4244#issuecomment-2198020961. I've also restored the comments that were removed; I saw that on an earlier PR of yours as well: please double check your IDE settings.

Please also note the check list we have on new PRs; in this case your changes did not compile, and a test was missing, and when added that test fails. That's not ideal for me as a reviewer, so if you could double check your work before submitting it, or clearly outline the state of your PR and where you might need help, that would help smoothen the process to get your changes accepted.

File: rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java [hunk 1]
```diff
@@ -65,10 +66,19 @@ private Expression replace(ExecutionContext ctx, J.MethodInvocation m, String pa
...
-                Expression replaced = JavaTemplate.apply(pattern, getCursor(), m.getCoordinates().replace(), e);
+                getCursor().getParentTreeCursor().putMessage("SIMPLIFY_BOOLEAN_EXPRESSION", true);
+                Expression replaced = JavaTemplate.apply(pattern, getCursor(), m.getCoordinates().replace(), m.getArguments().get(0));
                 return (Expression) new UnnecessaryParenthesesVisitor<>().visitNonNull(replaced, ctx, getCursor());
             }
+
+            @Override
+            public J postVisit(J tree, ExecutionContext ctx) {
+                J j = super.postVisit(tree, ctx);
+                if (getCursor().getNearestMessage("SIMPLIFY_BOOLEAN_EXPRESSION", false)) {
```
Comment (knutwannheden) [inline rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java:77]: I am AFK, but I would expect `pollMessage()` rather than `getNearestMessage()`. I doubt that will fix the problem, but that should be better.

**Review by timtebeek — APPROVED** [review]
Went for an alternative approach just to see this through. Thanks for getting this started @Riyazul555 !
