### PR TITLE
Fix unchanged Quark files appearing in changeset results

### LINKED ISSUE #3948: UpdateMavenWrapper is reported as changing a lot of files (but it does not)
## What version of OpenRewrite are you using?

I am using

- Maven plugin 5.18.0
- Rewrite Recipe BOM: 2.6.1

I checked if the `UpdateMavenWrapper` had recent changes but I don't see any.

## How are you running OpenRewrite?

Using Quarkus CLI and OpenRewrite Maven Plugin.

## What is the smallest, simplest way to reproduce the problem?

Not exactly sure yet as our recipes are pretty intricate.
I was wondering if the issue was something obvious/expected. If not, I will take the time to dig more into it and prepare a reproducer.

What I currently know is that:

```
#####
# Update Maven wrapper
#####
---
type: specs.openrewrite.org/v1beta/recipe
name: io.quarkus.updates.core.quarkus37.UpdateMavenWrapper
recipeList:
  - org.openrewrite.maven.UpdateMavenWrapper:
      distributionVersion: 3.9.x
      addIfMissing: false
```
is applied first and then our usual recipes.

As long as `org.openrewrite.maven.UpdateMavenWrapper` is declared, the change report is very suspicious so I suspect this recipe is doing something odd.
Or that it interacts with some other recipes we have.

## What did you expect to see?

I don't expect `org.openrewrite.maven.UpdateMavenWrapper` to be reported as applying changes to all the files.

## What did you see instead?

The `org.openrewrite.maven.UpdateMavenWrapper` is reported for each file modified as in:

```
[WARNING] Changes have been made to src/main/java/io/quarkus/bot/MarkClosedPullRequestInvalid.java by:
[WARNING]     io.quarkus.openrewrite.Quarkus
[WARNING]         io.quarkus.updates.core.quarkus37.UpdateMavenWrapper
[WARNING]             org.openrewrite.maven.UpdateMavenWrapper: {distributionVersion=3.9.x, addIfMissing=false}
[WARNING]         io.quarkus.updates.core.quarkus30.JavaxInjectMigrationToJakartaInject
[WARNING]             org.openrewrite.java.ChangePackage: {oldPackageName=javax.inject, newPackageName=jakarta.inject, recursive=true}
[WARNING] Changes have been made to src/main/java/io/quarkus/bot/PushToProjects.java by:
[WARNING]     io.quarkus.openrewrite.Quarkus
[WARNING]         io.quarkus.updates.core.quarkus37.UpdateMavenWrapper
[WARNING]             org.openrewrite.maven.UpdateMavenWrapper: {distributionVersion=3.9.x, addIfMissing=false}
[WARNING]         io.quarkus.updates.core.quarkus30.JavaxInjectMigrationToJakartaInject
[WARNING]             org.openrewrite.java.ChangePackage: {oldPackageName=javax.inject, newPackageName=jakarta.inject, recursive=true}
[WARNING]         io.quarkus.updates.core.quarkus30.JavaxJsonToJakartaJson
[WARNING]             org.openrewrite.java.ChangePackage: {oldPackageName=javax.json, newPackageName=jakarta.json, recursive=true}
```

Also, the recipe applying changes to one of the wrapper file is the last one of the recipes we apply and not `UpdateMavenWrapper` (yes I know, this is very odd):

```
[WARNING] Deleted file .mvn/wrapper/MavenWrapperDownloader.java by:
[WARNING]     io.quarkus.openrewrite.Quarkus
[WARNING]         org.openrewrite.java.camel.migrate.ChangeManagedFailoverLoadBalancerMBeanMethodName
[WARNING]             org.openrewrite.java.ChangeMethodName: {methodPattern=org.apache.camel.api.management.mbean.ManagedFailoverLoadBalancerMBean exceptionStatistics(), newMethodName=extendedInformation}
```

### PR DESCRIPTION
**Pull request by timtebeek**
## Summary
- `Result.isLocalAndHasNoChanges()` calls `printAll()` to compare before/after, but `Quark` throw `UnsupportedOperationException` from `printAll()`. The catch block returns `false`, so unchanged files (e.g. `.jks` keystores) are incorrectly reported as changed.
- Add explicit handling: Quarks are compared by source path.
- Wrapper update recipes (e.g. `UpdateMavenWrapper`) are unaffected because they replace `Quark` → `Remote`, which doesn't match the new Quark-to-Quark check.

- Fixes #3948

## Test plan
- [x] Added unit tests for unchanged Quark (same path) and changed Quark (different path)
- [x] Existing tests pass (`./gradlew :rewrite-core:test`)

### CODE REVIEW

**Comment by timtebeek** [comment]
Feel free to immediately merge this if you see it and agree, such that this can make it into the release to fix a long standing issue.

File: rewrite-core/src/main/java/org/openrewrite/Result.java [hunk 1]
```diff
@@ -268,11 +270,25 @@ public String toString() {
...
+                return false;
+            }
+            // Quarks don't support printAll(); compare by source path instead
+            if (before instanceof Quark && after instanceof Quark) {
+                return before.getSourcePath().equals(after.getSourcePath());
+            }
+            // Binary files don't support printAll(); compare by byte content
+            if (before instanceof Binary && after instanceof Binary) {
+                return Arrays.equals(((Binary) before).getBytes(), ((Binary) after).getBytes());
+            }
```
Comment (shanman190) [inline rewrite-core/src/main/java/org/openrewrite/Result.java]: Should we just kill off Binary finally? We don't create them anywhere so it's just dead code.

Comment (timtebeek) [reply rewrite-core/src/main/java/org/openrewrite/Result.java]: Might be a good one to drop when v3 LST is widely used. Until then it's hard to say if it's still serialized somewhere. For now I've removed handling here, as I was already doubting it.

Comment (shanman190) [reply rewrite-core/src/main/java/org/openrewrite/Result.java]: There _shouldn't_ be. It was created around the time that we started the `UpdateGradleWrapper` recipe. From there we changed directions and leaned into the `Remote` type. There also isn't even a parser to create the type either, so it would have to be manually generated in a test or externally for it to manifest.

Safe enough to just continue to ignore it though.
