### PR TITLE
MavenPomDownloader support download snapshot timestamp version

### LINKED ISSUE #3152: MavenPomDownloader fail download SNAPSHOT_TIMESTAMP version jar
i use a SNAPSHOT_TIMESTAMP version  dependency in my maven project .  As follows:
```
<dependency>
    <groupId>com.xxxxx.cloud</groupId>
    <artifactId>spring-cloud-xxxxx-thirdparty-commons</artifactId>
    <version>2020.0.2-20210127.131051-2</version>
</dependency>
```

when i use `MavenParser` . i find MavenPomDownloader fail download all SNAPSHOT_TIMESTAMP version jar. 
```
         </dependency>
        <!--~~(com.xxxxx.cloud:spring-cloud-xxxxx-thirdparty-commons:2020.0.2-20210127.131051-2 failed. Unable to download POM. Tried repositories:
https://repo.maven.apache.org/maven2: HTTP 404)~~>--><dependency>
            <groupId>com.xxxxx.cloud</groupId>
            <artifactId>spring-cloud-xxxxx-thirdparty-commons</artifactId>
            <version>2020.0.2-20210127.131051-2</version>
        </dependency>
```

the reason :

image

i find that the download uri is error.

### PR DESCRIPTION
**Pull request by JoeCqupt**
fix #3152

### CODE REVIEW

**Comment by JoeCqupt** [comment]
Inspired by `org.eclipse.aether.artifact.AbstractArtifact#getBaseVersion` 

https://github.com/apache/maven-resolver/blob/master/maven-resolver-api/src/main/java/org/eclipse/aether/artifact/AbstractArtifact.java#L50

File: rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java [hunk 1]
```diff
@@ -64,6 +66,11 @@ public class MavenPomDownloader {
 
     private static final Retry mavenDownloaderRetry = retryRegistry.retry("MavenDownloader");
 
+    private static final Pattern SNAPSHOT_TIMESTAMP = Pattern.compile( "^(.*-)?([0-9]{8}\\.[0-9]{6}-[0-9]+)$" );
```
Comment (timtebeek) [inline rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java:69]:
```suggestion
    private static final Pattern SNAPSHOT_TIMESTAMP = Pattern.compile("^(.*-)?([0-9]{8}\\.[0-9]{6}-[0-9]+)$");
```

File: rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java [hunk 2]
```diff
@@ -555,13 +565,32 @@ public Pom download(GroupArtifactVersion gav,
...
+     */
+    private GroupArtifactVersion handleSnapshotTimestampVersion(GroupArtifactVersion gav) {
+
+        Matcher m = SNAPSHOT_TIMESTAMP.matcher(gav.getVersion());
+        if (m.matches()) {
+            if (m.group(1) != null) {
+                String baseVersion = m.group(1) + SNAPSHOT;
+                return gav.withVersion(baseVersion);
+            }
+        }
```
Comment (timtebeek) [inline rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java:590]: In aether there are a few more code paths covered; https://github.com/apache/maven-resolver/blob/7d17bc3a8eff2cafe9fd486c407fa737e37d9ae0/maven-resolver-api/src/main/java/org/eclipse/aether/artifact/AbstractArtifact.java#L50-L70

What made you for instance skip the case where `m.group(1) == null`?
I've not looked as deep into this as you have, but was wondering when comparing.
And since the additional tests seem to cover only one specific case, I'd thought to ask.

Comment (JoeCqupt) [reply rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java]: i made a mistake , i have added the case where m.group(1) == null

**Review by timtebeek — APPROVED** [review]
Thanks a lot @JoeCqupt !
