### PR TITLE
Fix various issues in yaml/JsonPathMatcher

### LINKED ISSUE #1419: YAML: strange behaviour with JSON path matcher and ChangeValue rule
While working with YAMLs, the JSON path matcher and the `ChangeValue` recipe I'm experiencing some strange behaviour. 

While using the recursive descent operator (e.g. [`$..[?(@.kind == 'ServiceAccount')].kind`](https://github.com/kevinvandervlist/rewrite/blob/3076d853777a2063c5e28f51960980349241526f/rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/JsonPathMatcherIssuesTest.kt#L54)), I get a stack overflow error:
```
java.lang.StackOverflowError
	at java.base/java.util.LinkedList.listIterator(LinkedList.java:872)
	at java.base/java.util.AbstractList.listIterator(AbstractList.java:311)
	at java.base/java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:238)
	at org.openrewrite.yaml.JsonPathMatcher$JsonPathYamlVisitor.visitRecursiveDescent(JsonPathMatcher.java:148)
	at org.openrewrite.yaml.internal.grammar.JsonPath$RecursiveDescentContext.accept(JsonPath.java:272)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.openrewrite.yaml.JsonPathMatcher$JsonPathYamlVisitor.visitRecursiveDescent(JsonPathMatcher.java:151)
	at org.openrewrite.yaml.internal.grammar.JsonPath$RecursiveDescentContext.accept(JsonPath.java:272)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
```

In other cases, such as [`$.*[?(@.kind == 'ServiceAccount')].kind`](https://github.com/kevinvandervlist/rewrite/blob/3076d853777a2063c5e28f51960980349241526f/rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/JsonPathMatcherIssuesTest.kt#L56), I don't seem to get any matches while that is to be expected. 

According to [the documentation here](https://docs.openrewrite.org/reference/jsonpath-and-jsonpathmatcher-reference) I expect my test cases to work, even if it currently is only a partial implementation.

I've made a commit in [my fork](https://github.com/kevinvandervlist/rewrite/commit/4b2b8a798a1af4a4b708d37428849341e4d08ad5) containing a couple of unit test demonstrating the issues I have.

### PR DESCRIPTION
**Pull request by traceyyoshima**
**Changes:**
- Updated JsonPathParser and JsonPathLexer to produce the correct JsonPaths.
- Refactored JsonPathMatcher test harness and updated tests.

**Updates to yaml/JsonPathMatcher:**
- Added support for reference by index(es).
- Added support for reference by name(s).
- Completed support for slicing lists.
- Improved support for filters.
- Fixed false positives from filters due to incorrect scopes.
- Fixed false negatives due to incorrect scopes.

**API changes:**
- Removed encloses method in favor of filters.

**Known issue:**
- The test allPropertiesInKeyFromRoot and multipleWildcards may still produces false positives.

**Notes:**
- Prior to creating a PR I had a Lexer, Parser, and JsonPathMatcher V2 to compare test results with the original versions to prevent regressions.
- Logical operators are still not supported.

fixes #1419

### CODE REVIEW

File: rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java [hunk 1]
```diff
@@ -136,88 +124,99 @@ public Object visitJsonpath(JsonPath.JsonpathContext ctx) {
...
-                Yaml.Sequence s = (Yaml.Sequence) context;
-                return s.getEntries().stream()
-                        .map(Yaml.Sequence.Entry::getBlock)
+
+                // Return a list if more than 1 property is specified.
+                return ctx.property().stream()
+                        .map(this::visitProperty)
                         .collect(Collectors.toList());
+            } else if (ctx.slice() != null) {
+                return visitSlice(ctx.slice());
```
Comment (jbrisbin) [inline rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java:178]: Nice! Like the better organization of the flow.

File: rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java [hunk 2]
```diff
@@ -227,145 +226,403 @@ public Object visitRangeOp(JsonPath.RangeOpContext ctx) {
...
+        @Override
+        public Object visitBinaryExpression(JsonPathParser.BinaryExpressionContext ctx) {
+            Object lhs = ctx.children.get(0);
+            Object rhs = ctx.children.get(2);
+
+            lhs = getBinaryExpressionResult(lhs);
+            rhs = getBinaryExpressionResult(rhs);
+
+            if (ctx.LOGICAL_OPERATOR() != null) {
+                throw new UnsupportedOperationException("Logical operators are not supported. Please open an issue if you need this functionality.");
```
Comment (jbrisbin) [inline rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java:478]: 👍
