### PR TITLE
Fix AddOrUpdateAnnotationAttribute unable to handle FieldAccess

### LINKED ISSUE #4897: AddOrUpdateAnnotationAttribute unable to handle @Anno(key = ClassB.staticVar)
## What version of OpenRewrite are you using?
I am using

- OpenRewrite 8.42.0
- Mavenplugin 5.47.0

## How are you running OpenRewrite?

Unit Test, maven plugin

## What is the smallest, simplest way to reproduce the problem?

```java
              package com.example;

              public class Const {
                    public static final String PATH = "path";
              }
```

```java
              import jakarta.ws.rs.Path;
              import com.example.Const;
              
              @Path(value = Const.PATH)
              public class Example {
                  private void methodName() { }
              }
```

## What did you expect to see?

No errors.

## What did you see instead?

`Failed to parse sources or run recipe`

## What is the full stack trace of any errors you encountered?
```
Caused by: java.lang.ClassCastException: class org.openrewrite.java.tree.J$FieldAccess cannot be cast to class org.openrewrite.java.tree.J$Literal (org.openrewrite.java.tree.J$FieldAccess and org.openrewrite.java.tree.J$Literal are in unnamed module of loader 'app')
	at org.openrewrite.java.AddOrUpdateAnnotationAttribute$1.lambda$visitAnnotation$2(AddOrUpdateAnnotationAttribute.java:189)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:243)
	at org.openrewrite.internal.ListUtils.map(ListUtils.java:265)
	at org.openrewrite.java.AddOrUpdateAnnotationAttribute$1.visitAnnotation(AddOrUpdateAnnotationAttribute.java:123)
	at org.openrewrite.java.AddOrUpdateAnnotationAttribute$1.visitAnnotation(AddOrUpdateAnnotationAttribute.java:85)
	at org.openrewrite.java.tree.J$Annotation.acceptJava(J.java:233)
	at org.openrewrite.java.tree.J.accept(J.java:59)
	at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:250)
	... 44 more
```

## Are you interested in [contributing a fix to OpenRewrite]
Yes, I am trying to make a fix

### PR DESCRIPTION
**Pull request by SiBorea**
## What's changed?
- Fixes #4897 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

File: rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java [hunk 1]
```diff
@@ -893,6 +892,47 @@ public class A {
         );
     }
 
+    @Test
+    void updateFieldAccessAttribute() {
+        rewriteRun(
```
Comment (MBoegers) [inline rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java:897]: Can you try to apply the recipe to change the value from `hello` to `Cost.HI`?

File: rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java [hunk 2]
```diff
@@ -46,37 +42,37 @@ public String getDisplayName() {
     @Override
     public String getDescription() {
         return "Some annotations accept arguments. This recipe sets an existing argument to the specified value, " +
-               "or adds the argument if it is not already set.";
+          "or adds the argument if it is not already set.";
```
Comment (MBoegers) [inline rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java:45]: I think you have a custom style configured in your IDE. We use the IntelliJ internal formatter with standard configuration. 
Please reformat to keep the change as small as needed.

File: rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java [hunk 3]
```diff
@@ -174,23 +170,31 @@ public J.Annotation visitAnnotation(J.Annotation a, ExecutionContext ctx) {
...
-                                    return it;
+                                Expression exp = as.getAssignment();
+                                if (exp instanceof J.Literal) {
+                                    J.Literal value = (J.Literal) exp;
+                                    if (newAttributeValue.equals(value.getValueSource()) || Boolean.TRUE.equals(addOnly)) {
+                                        return it;
+                                    }
+                                    return as.withAssignment(value.withValue(newAttributeValue).withValueSource(newAttributeValue));
+                                } else if (exp instanceof J.FieldAccess) {
+                                    as = JavaTemplate.builder("#{} = #{}")
```
Comment (MBoegers) [inline rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java:193]: You are omitting here to check if the `newAttributeValue` is already set or the recipes executes in the `addOnly` mode, see line 188. Please check to prevent unnecessary operations.

File: rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java [hunk 4]
```diff
@@ -174,23 +170,31 @@ public J.Annotation visitAnnotation(J.Annotation a, ExecutionContext ctx) {
...
+                                      .build()
+                                      .apply(new Cursor(getCursor(), as), as.getCoordinates().replace(), var.getSimpleName(), newAttributeValue);
```
Comment (MBoegers) [inline rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java:195]: Why do you think you need a new `Cursor` here? `getCursor()` should do the trick

**Comment by MBoegers** [comment]
Hi @SiBorea I also stumbled across this a few hours ago, thanks for the fix. If you have any questions regarding my comments, feel free to ask. :)

**Review by MBoegers — CHANGES_REQUESTED** [review]

File: rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java (hunk 1 above)
Comment (SiBorea) [reply rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java:897]: The `attributeValue` of the recipe is of type String, don't think we can change the value from `hello` to `Const.HI`

File: rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java (hunk 4 above)
Comment (SiBorea) [reply rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java:195]: Using `getCursor()` here will return a `J.Annotation` object, rather than `J.FieldAccess` we need.

File: rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java (hunk 1 above)
Comment (SiBorea) [reply rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java:897]: I tested it a little bit, the result shows that it can only change the value to `"Const.HI"`, not `Const.HI`

File: rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java (hunk 3 above)
Comment (SiBorea) [reply rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java:193]: I omitted `newAttributeValue` since they will never be equal. Forgot to add `addOnly`.

File: rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java [hunk 5]
```diff
@@ -46,7 +46,7 @@ public String getDisplayName() {
     @Override
     public String getDescription() {
         return "Some annotations accept arguments. This recipe sets an existing argument to the specified value, " +
-               "or adds the argument if it is not already set.";
+                "or adds the argument if it is not already set.";
```
Comment (SiBorea) [inline rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java:49]: I restored my IntelliJ to default code style, this should be fine according to the default setting

File: rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java (hunk 4 above)
Comment (MBoegers) [reply rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java]: A I see, thats right. Within this recipe the situation is solved by generating an new Annotation with one Assigment and then call `get(0)`, see https://github.com/openrewrite/rewrite/blob/ae8acf40c3faaea8ac16e7b752ddf17603ff7429/rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java#L239

File: rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java (hunk 1 above)
Comment (MBoegers) [reply rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java:898]: It _should_ be possible. The `attributeValue`'s value is interpreted as whatever it is. Did you try the FQN `Const.HI`?
If you don't mind, I would have a look myself.

Comment (SiBorea) [reply rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java:912]: Sure, please go ahead.

Comment (MBoegers) [reply rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java:912]: I will retest this later in my branch ;)

**Comment by MBoegers** [comment]
Thanks @SiBorea, for your work here <3
