### PR TITLE
fixes #383 add full wildcard support to method matcher.

### LINKED ISSUE #383: MethodMatcher with full wildcard for class does not correctly match a class within a package
Per the [`MethodMatcher` documentation](https://github.com/openrewrite/rewrite/blob/a1b50b8a3cb79efc77bd8c298b64abbb52e1e43a/rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java#L53), the following syntax should match any `foo` method on any class: `* foo(..)`.

If the class is not in a package, it correctly matches:

```
class A {
    void foo() {}
}
```

If the class is in a package (any package), it fails to match:

```
package a;

class A {
    void foo() {}
}
```

PR with failed test: https://github.com/openrewrite/rewrite/pull/384

### PR DESCRIPTION
**Pull request by traceyyoshima**
fixes #383

### CODE REVIEW

File: rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java [hunk 1]
```diff
@@ -322,12 +322,14 @@ private AspectjUtils() {
...
      * <p>
+     * A full wildcard "*" will match any sequences of characters included package separators.
+     * <p>
      * The ".." wildcard matches any sequence of characters that start and end with a ".", so it can be used to pick out all
      * types in any subpackage, or all inner types. e.g. <code>within(com.xerox..*)</code> picks out all join points where
      * the code is in any declaration of a type whose name begins with "com.xerox.".
      */
     public static String aspectjNameToPattern(String name) {
-        return name
+        return name.equals("*") ? "[^.].*" : name
```
Comment (traceyyoshima) [inline rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java:332]: Regex ([a-zA-Z_$][a-zA-Z\d_$]*\.)*[a-zA-Z_$][a-zA-Z\d_$]*
may be considered more accurate, but I kept the pattern similar to what exists already.
