### PR TITLE
Use `Object.notifyAll()` instead of `Object.notify()`

### LINKED ISSUE #1645: `Thread.notifyAll` should be used. `RSPEC-2446`
> notify and notifyAll both wake up sleeping threads, but notify only rouses one, while notifyAll rouses all of them. Since notify might not wake up the right thread, notifyAll should be used instead.

See : https://rules.sonarsource.com/java/quickfix/RSPEC-2446

Examples From : https://wiki.sei.cmu.edu/confluence/display/java/THI02-J.+Notify+all+waiting+threads+rather+than+a+single+thread

```java


public final class ProcessStep implements Runnable {
  private static final Object lock = new Object();
  private static int time = 0;
  private final int step; // Do Perform operations when field time
                          // reaches this value
 
  public ProcessStep(int step) {
    this.step = step;
  }
 
  @Override public void run() {
    try {
      synchronized (lock) {
        while (time != step) {
          lock.wait();
        }
 
        // Perform operations
 
        time++;
        lock.notify();
      }
    } catch (InterruptedException ie) {
      Thread.currentThread().interrupt(); // Reset interrupted status
    }
  }
 
  public static void main(String[] args) {
    for (int i = 4; i >= 0; i--) {
      new Thread(new ProcessStep(i)).start();
    }
  }
} 

```

```java
public final class ProcessStep implements Runnable {
  private static final Object lock = new Object();
  private static int time = 0;
  private final int step; // Perform operations when field time
                          // reaches this value
  public ProcessStep(int step) {
    this.step = step;
  }
 
  @Override public void run() {
    try {
      synchronized (lock) {
        while (time != step) {
          lock.wait();
        }
   
        // Perform operations
   
        time++;
        lock.notifyAll(); // Use notifyAll() instead of notify()
      }
    } catch (InterruptedException ie) {
      Thread.currentThread().interrupt(); // Reset interrupted status
    }
  }
 
}
```

### PR DESCRIPTION
**Pull request by yeikel**
Closes #1645

### CODE REVIEW

**Comment by knutwannheden** [comment]
@yeikel There are many references to `Thread.notifyAll()`. While this recipe is about threading, I think that `Object.notifyAll()` is what is meant?

**Comment by yeikel** [comment]
> @yeikel There are many references to `Thread.notifyAll()`. While this recipe is about threading, I think that `Object.notifyAll()` is what is meant?

I was unsure if I should do that given that this is often used within the thread context as far as I know. It is true, however, that the recipe is using Object to match

I can update it

File: rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+import org.openrewrite.java.MethodMatcher;
+import org.openrewrite.java.search.UsesMethod;
+import org.openrewrite.java.tree.J;
+
+import java.time.Duration;
+import java.util.Collections;
+import java.util.Set;
+
+/**
+ * Recipe to use {@link Object#notifyAll()} instead of {@link Object#notify()}
```
Comment (jkschneider) [inline rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java:32]: All of this context in this javadoc is great, and I'd love to see it move down into the `getDescription()` on the recipe so that people see all of it when using the recipe.

Comment (yeikel) [reply rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java]: Thank you for the feedback @jkschneider. I extracted them with d7d4c9ee1288d1880d20d99c02e88e5445a981f8

File: rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    private static final MethodMatcher OBJECT_NOTIFY = new MethodMatcher("java.lang.Object notify()");
+
+    @Override
+    public String getDisplayName() {
+        return "Replaces `Object.notify()` with `Object.notifyAll()`";
+    }
+
+    @Override
+    public String getDescription() {
+        return "`Object.notifyAll()` and `Object.notify()` both wake up sleeping threads, but `Object.notifyAll()` only rouses one while`Object.notifyAll()` rouses all of them. " +
```
Comment (timtebeek) [inline rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java:42]:
```suggestion
        return "`Object.notifyAll()` and `Object.notify()` both wake up sleeping threads, but `Object.notify()` only rouses one while`Object.notifyAll()` rouses all of them. " +
```
Hope this is correct; it felt off reading it from the context.

Comment (yeikel) [reply rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java]: That was a typo that resulted from copying/pasting. Thank you for catching it :)

File: rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+
+    @Override
+    public String getDisplayName() {
+        return "Replaces `Object.notify()` with `Object.notifyAll()`";
+    }
+
+    @Override
+    public String getDescription() {
+        return "`Object.notifyAll()` and `Object.notify()` both wake up sleeping threads, but `Object.notify()` only rouses one while `Object.notifyAll()` rouses all of them. " +
+                "Since `Object.notify()` might not wake up the right thread, `Object.notifyAll()` should be used instead.See [this](https://wiki.sei.cmu.edu/confluence/display/java/THI02-J.+Notify+all+waiting+threads+rather+than+a+single+thread) for more information.";
```
Comment (timtebeek) [inline rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java:43]: A space was missing; figured add a newline as well for readability.
```suggestion
                "Since `Object.notify()` might not wake up the right thread, `Object.notifyAll()` should be used instead. " +
                "See [this](https://wiki.sei.cmu.edu/confluence/display/java/THI02-J.+Notify+all+waiting+threads+rather+than+a+single+thread) for more information.";
```

**Comment by sambsnyd** [comment]
Thanks @yeikel !
