### PR TITLE
Skip redundant property override in child when parent declares same dependency

### LINKED ISSUE #6945: UpgradeDependencyVersion with overrideManagedVersion does not add property if <relativePath> is missing
Adding this test case in UpgradeDependencyVersionTests fails - the recipe makes no changes
```java
    @Test
    void upgradeVersionDefinedViaImplicitPropertyInRemoteParentOfLocalParent_withoutRelativePath() {
        rewriteRun(
          spec -> spec.recipe(new UpgradeDependencyVersion("org.flywaydb", "flyway-core", "10.15.0", "", true, null)),
          pomXml(
            """
              <project>
                  <parent>
                      <groupId>org.springframework.boot</groupId>
                      <artifactId>spring-boot-dependencies</artifactId>
                      <version>3.3.0</version>
                  </parent>
                  <groupId>com.mycompany</groupId>
                  <artifactId>my-parent</artifactId>
                  <version>1</version>
                  <dependencies>
                      <dependency>
                          <groupId>org.flywaydb</groupId>
                          <artifactId>flyway-core</artifactId>
                      </dependency>
                  </dependencies>
              </project>
              """,
            """
              <project>
                  <parent>
                      <groupId>org.springframework.boot</groupId>
                      <artifactId>spring-boot-dependencies</artifactId>
                      <version>3.3.0</version>
                  </parent>
                  <groupId>com.mycompany</groupId>
                  <artifactId>my-parent</artifactId>
                  <version>1</version>
                  <properties>
                      <flyway.version>10.15.0</flyway.version>
                  </properties>
                  <dependencies>
                      <dependency>
                          <groupId>org.flywaydb</groupId>
                          <artifactId>flyway-core</artifactId>
                      </dependency>
                  </dependencies>
              </project>
              """
          ),
          mavenProject("my-child",
            pomXml(
              """
                <project>
                    <parent>
                        <groupId>com.mycompany</groupId>
                        <artifactId>my-parent</artifactId>
                        <version>1</version>
                    </parent>
                    <groupId>com.mycompany</groupId>
                    <artifactId>my-child</artifactId>
                    <version>1</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.flywaydb</groupId>
                            <artifactId>flyway-core</artifactId>
                        </dependency>
                    </dependencies>
                </project>
                """
            )
          )
        );
    }
 ```

The root cause is `AddProperty` where the is this check
```java
// If there is a parent pom in the same project, update the property there instead
                if (document.getRoot().getChild("parent")
                        .flatMap(tag -> tag.getChild("relativePath"))
                        .flatMap(Xml.Tag::getValue)
                        .flatMap(v -> v.trim().isEmpty() ? Optional.empty() : Optional.of(v))
                        .isPresent()
```
However relativePath can be ommited and then it's implicitly "../pom.xml" a more proper check could be:
```java
if (getResolutionResult().parentPomIsProjectPom())
```
But this breaks some callers of the AddProperty.

### PR DESCRIPTION
**Pull request by MBoegers**
## Summary
- When `UpgradeDependencyVersion` processes a managed dependency whose version is a property (e.g. `${flyway.version}`), it now checks if a local parent POM also declares the same `<dependency>`. If so, the parent will be processed by the same recipe and will handle the property change — the child skips the redundant override.
- Adds `isDeclaredByLocalParent()` helper that walks up the local parent chain checking for declared dependencies (not just managed ones), complementing the existing `isManagedByLocalParent()` method.

- Fixes #6945

## Test plan
- [x] `UpgradeDependencyVersionTest.upgradeVersionDefinedViaImplicitPropertyInRemoteParentOfLocalParent_withoutRelativePath` — parent and child both declare flyway-core, property only added to parent
- [x] Full `UpgradeDependencyVersionTest` suite passes (no regressions)
- [x] `ChangePropertyValueTest` and `AddPropertyTest` suites pass

### CODE REVIEW

File: rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java [hunk 1]
```diff
@@ -330,9 +351,12 @@ private Xml.Tag upgradeDependency(ExecutionContext ctx, Xml.Tag t) throws MavenD
                             // if a managed dependency is expressed as a property, change the property value
                             // do this only when a requested bom is absent, otherwise changing property has no effect
                             if (dm != null && isProperty(dm.getRequested().getVersion()) && dm.getRequestedBom() == null) {
-                                doAfterVisit(new ChangePropertyValue(dm.getRequested().getVersion().substring(2,
-                                        dm.getRequested().getVersion().length() - 1),
-                                        newerVersion, overrideManagedVersion, false).getVisitor());
+                                // if a local parent also declares this dependency, it will handle the property change
+                                if (!isDeclaredByLocalParent(d.getGroupId(), d.getArtifactId())) {
```
Comment (timtebeek) [inline rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java:357]: Should we maybe only skip if the version is `null` here? To avoid that we keep a version that then pins back a newer version from a parent? Or is that concern already handled separately?

Comment (MBoegers) [reply rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java:357]: yes good call applied
