### PR TITLE
Fix a defect of `RewriteTest.rewriteRun()`  that cannot detect unexpected newly generated files

### LINKED ISSUE #2796: Rewrite unit tests cannot detect unexpected newly generated files
I found a defect that `RewriteTest.rewriteRun()` cannot detect unexpected newly generated files.
An example test is
```java
    @Test
    void demonstrateRewriteRunDefect() {
        rewriteRun(
          spec -> spec.recipe(new AppendToTextFile("file1.txt", "content1", "preamble1", true, "replace")
            .doNext(new AppendToTextFile("file2.txt", "content2", "preamble2", true, "replace"))),
          text(
            "existing2",
            """
              preamble2
              content2
              """,
            spec -> spec.path("file2.txt").noTrim()
          )
        );
    }
```
 Recipe `AppendToTextFile` is expected to create new files `file1.txt` here, so the expected results are
```diff
Results = 

diff --git a/file1.txt b/file1.txt
new file mode 100644
index 0000000..0ece344
--- /dev/null
+++ b/file1.txt
@@ -0,0 +1,2 @@ org.openrewrite.text.AppendToTextFile
+preamble1
+content1

diff --git a/file2.txt b/file2.txt
index 2647aa3..d9b1872 100644
--- a/file2.txt
+++ b/file2.txt
@@ -1 +1,2 @@ org.openrewrite.text.AppendToTextFile
-existing2
\ No newline at end of file
+preamble2
+content2
```

The above test should fail since `file1.txt` is generated and should be detected, but it didn't and passed.

### PR DESCRIPTION
**Pull request by kunli2**
Fixes #2796

I found a defect that `RewriteTest.rewriteRun()` cannot detect unexpected newly generated files.
An example test is
```java
    @Test
    void demonstrateRewriteRunDefect() {
        rewriteRun(
          spec -> spec.recipe(new AppendToTextFile("file1.txt", "content1", "preamble1", true, "replace")
            .doNext(new AppendToTextFile("file2.txt", "content2", "preamble2", true, "replace"))),
          text(
            "existing2",
            """
              preamble2
              content2
              """,
            spec -> spec.path("file2.txt").noTrim()
          )
        );
    }
```
 Recipe `AppendToTextFile` is expected to create new files `file1.txt` here, so the expected results are
```diff
Results = 

diff --git a/file1.txt b/file1.txt
new file mode 100644
index 0000000..0ece344
--- /dev/null
+++ b/file1.txt
@@ -0,0 +1,2 @@ org.openrewrite.text.AppendToTextFile
+preamble1
+content1

diff --git a/file2.txt b/file2.txt
index 2647aa3..d9b1872 100644
--- a/file2.txt
+++ b/file2.txt
@@ -1 +1,2 @@ org.openrewrite.text.AppendToTextFile
-existing2
\ No newline at end of file
+preamble2
+content2
```

The above test should fail since `file1.txt` is generated and should be detected, but it didn't and passed.

### CODE REVIEW

File: rewrite-core/src/test/java/org/openrewrite/text/AppendToTextFileTest.java [hunk 1]
```diff
@@ -157,6 +158,48 @@ void multipleFiles() {
         );
     }
 
+    // This test is just to demonstrate RewriteRun defect, it's expected to fail since new file `file1.txt` generated but pass.
+    // todo, kunli, to be removed after this PR.
+    @Disabled("Expected to be failed since new file generated")
+    @Test
+    void demonstrateRewriteRunDefect() {
+        rewriteRun(
```
Comment (sambsnyd) [inline rewrite-core/src/test/java/org/openrewrite/text/AppendToTextFileTest.java:166]: JUnit has an assertion method which accepts a lambda and asserts that the lambda will throw an exception. If this is expected to fail then we can wrap it in `Assertions.assertThrows()` and remove the `@Disabled`

Comment (kunli2) [reply rewrite-core/src/test/java/org/openrewrite/text/AppendToTextFileTest.java]: good point, I thought I should remove this test after this PR,  but good to keep it, updated to use `assertThrows`.
