### PR TITLE
Autodetect formatting style of JSON code

### LINKED ISSUE #4246: Json formatting/style doesn't seem to be respected when adding values/members
## What version of OpenRewrite are you using?

- OpenRewrite 2.12.0
- Maven plugin 5.23.3

## Context
I have created a recipe that adds key+value into a json. It is done via `Json.Literal` and is inspired by `json.ChangeValue`. Here's the relevant code:

```java
JsonRightPadded<JsonKey> newKey = new JsonRightPadded<>(
    new Json.Literal(randomId(), Space.EMPTY, Markers.EMPTY, "\"" + key + "\"", key),
    Space.EMPTY,
    Markers.EMPTY
);
Json.Literal newValue = new Json.Literal(randomId(), Space.build(" ", emptyList()), Markers.EMPTY, value, unQuote(value));
Json newMember = new Json.Member(randomId(), space, Markers.EMPTY, newKey, newValue);

List<Json> members = jsonIsEmpty ? new ArrayList<>() : obj.getMembers();
members.add(newMember);
return obj.withMembers(members);
```

## Problem
* I don't seem to be able to control the padding after the value is inserted
* If this isn't the only value in the object, the automatic insertion of the comma is on its own line.

My test:
```java
...
rewriteRun(
        spec -> spec.recipe(new AddKeyValue(
            "$.", "key", "\"val\""
        )),
        //language=json
        json("""
                {
                    "l": [ 1, 2 ]
                }
            """,
            """
                {
                    "l": [ 1, 2 ],
                    "key": "val"
                }
            """)
    );
...
```
fails with:
```
expected: 
  "{
      "l": [ 1, 2 ],
      "key": "val"
  }"
 but was: 
  "{
      "l": [ 1, 2 ]
  ,
      "key": "val"}"
```

The same thing happens with Arrays and their Values.

## Expected Behaviour
Can be seen in the test failure:
* When adding an element the comma is added on the same line as the previous element.
* The closing bracket is not moved from it's initial position

In general I think this is a styling issue, which I understand is not supported for json? I could not find any `json.style.*` classes, pretty sure `TabsAndIndentsStyle` for xml solves this issue. CMIIW. Thanks 🙂

### PR DESCRIPTION
**Pull request by greg-at-moderne**
## What's changed?

Adding:
- support for autodetecting JSON formatting style
- and `AddKeyValue` recipe using it

The PR comes as patchwork of:
- the recipe implementation done in #4341 by @dpozinen 
- the style autodetection basically copied from respective classes for XML and YAML

## What's your motivation?

- Fixes #4246

## Anything in particular you'd like reviewers to focus on?

- The style autodetection is a basic implementation focusing on just indents and tabs. There's no support for other qualities/features of code.
- No support for full code reformatting.

### CODE REVIEW

File: rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+    String keyPath;
+
+    @Option(displayName = "Key",
+            description = "The key to create.",
+            example = "myKey")
+    String key;
+
+    @Option(displayName = "Value",
+            description = "The value to add to the array at the specified key. Can be of any type." +
+                          " String values should be quoted to be inserted as Strings.",
```
Comment (knutwannheden) [inline rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java:53]: The description here appears to imply that a value will get added to an array, if the value is an array. Looking at the implementation that doesn't appear to be the case. Can we check how we handle this in YAML? Should this be supported or is that better handled by another recipe? In any case I think we ought to clarify that.

File: rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+            }
+
+            private JsonRightPadded<JsonKey> rightPaddedKey() {
+                return new JsonRightPadded<>(
+                        new Json.Literal(randomId(), Space.EMPTY, Markers.EMPTY, "\"" + key + "\"", key),
+                        Space.EMPTY, Markers.EMPTY
+                );
+            }
+
+            private String unQuote(String value) {
```
Comment (knutwannheden) [inline rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java:114]: The value is only expected to be a string when it is quoted. Otherwise a Number or Boolean object would actually be expected. Or even the final result a `Json.JsonObject` or `Json.Array` instead of a `Json.Literal`. Possibly we could just use the `JsonParser`?

File: rewrite-json/src/main/java/org/openrewrite/json/format/Indents.java [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+import org.openrewrite.json.style.TabsAndIndentsStyle;
+import org.openrewrite.json.tree.Json;
+import org.openrewrite.style.NamedStyles;
+
+import static java.util.Collections.singletonList;
+
+public class Indents extends Recipe {
+    @Override
+    public String getDisplayName() {
+        return "YAML indent";
```
Comment (knutwannheden) [inline rewrite-json/src/main/java/org/openrewrite/json/format/Indents.java:32]:
```suggestion
        return "JSON indent";
```

File: rewrite-json/src/main/java/org/openrewrite/json/format/Indents.java [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+    }
+
+    @Override
+    public String getDescription() {
+        return "Format tabs and indents in YAML.";
```
Comment (knutwannheden) [inline rewrite-json/src/main/java/org/openrewrite/json/format/Indents.java:37]:
```suggestion
        return "Format tabs and indents in JSON.";
```

File: rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java [hunk 5]
```diff
@@ -0,0 +1,237 @@
...
+ * <p>
+ * https://www.apache.org/licenses/LICENSE-2.0
+ * <p>
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.openrewrite.json.style;
```
Comment (knutwannheden) [inline rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java:16]: As this package didn't exist until now, please add a `package-info.java` file as we have in all other packages.

File: rewrite-json/src/main/java/org/openrewrite/json/format/AutoFormatVisitor.java [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+ * <p>
+ * https://www.apache.org/licenses/LICENSE-2.0
+ * <p>
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.openrewrite.json.format;
```
Comment (knutwannheden) [inline rewrite-json/src/main/java/org/openrewrite/json/format/AutoFormatVisitor.java:16]: As this package didn't exist until now, please add a `package-info.java` file as we have in all other packages.

File: rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java [hunk 7]
```diff
@@ -0,0 +1,237 @@
...
+
+            return new TabsAndIndentsStyle(
+                    useTabs,
+                    useTabs ? indent : 1,
+                    useTabs ? 1 : indent
+            );
+        }
+    }
+
+    private static class FindLineFormatJavaVisitor extends JsonVisitor<GeneralFormatStatistics> {
```
Comment (knutwannheden) [inline rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java:126]:
```suggestion
    private static class FindLineFormatJsonVisitor extends JsonVisitor<GeneralFormatStatistics> {
```

Comment (greg-at-moderne) [reply rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java]: 1e276396f instead.

File: rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java (hunk 5 above)
Comment (greg-at-moderne) [reply rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java:16]: 160d31050

File: rewrite-json/src/main/java/org/openrewrite/json/format/AutoFormatVisitor.java (hunk 6 above)
Comment (greg-at-moderne) [reply rewrite-json/src/main/java/org/openrewrite/json/format/AutoFormatVisitor.java:16]: 160d31050

File: rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java (hunk 2 above)
Comment (greg-at-moderne) [reply rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java:114]: 199f5c546

File: rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java (hunk 1 above)
Comment (greg-at-moderne) [reply rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java]: eda9f61ae to clarify the current status.

Comment (greg-at-moderne) [reply rewrite-json/src/main/java/org/openrewrite/json/AddKeyValue.java]: > Can we check how we handle this in YAML? Should this be supported or is that better handled by another recipe? In any case I think we ought to clarify that.

- In YAML we have a dedicated recipe to append to an array (sequence): https://github.com/openrewrite/rewrite/blob/main/rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequence.java
- Other than `MergeYaml` there's no direct counterpart of the `AddKeyValue` in YAML. There's a bunch of `Change*` recipes
- There's `CopyValue` recipe, but that doesn't seem to work with sequences/arrays either.

=> I suggest we just keep the `AddKeyValue` recipe as is currently. And then optionally at some point we might decide to implement `AppendToArray` recipe or some more generic array manipulation (`AppendOrUpdateArray`, etc.).
