### PR TITLE
Resolve groovy multiline interpolation parse error

### LINKED ISSUE #7429: Groovy parser fails to parse multiline strings
## What version of OpenRewrite are you using?
I am using

- OpenRewrite main branch (v8.79.6)

## How are you running OpenRewrite?

I am running a new unit test in `rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java`:
```
diff --git a/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java b/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
index 81ee71d23..6f2428e28 100644
--- a/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
+++ b/rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
@@ -337,4 +337,29 @@ def method() {
         );
     }
 
+    @Test
+    void testMultilineString() {
+        rewriteRun(
+          groovy(
+            """
+                String name = \"\"\"
+                    foo
+                \"\"\"
+                """
+          )
+        );
+    }
+    @Test
+    void testMultilineStringInterpolation() {
+        rewriteRun(
+          groovy(
+            """
+                String name = \"\"\"
+                    ${foo}
+                \"\"\"
+                """
+          )
+        );
+    }
+
 }

```

## What is the smallest, simplest way to reproduce the problem?

```groovy
String test = """
 ${foo}
"""
```

## What did you expect to see?

Code parsed successfully

## What did you see instead?

Parser failure

## What is the full stack trace of any errors you encountered?
```

> Configure project :
Inferred project: rewrite, version: 8.80.0-SNAPSHOT
> Task :rewrite-kotlin:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :rewrite-java-21:processResources NO-SOURCE
> Task :rewrite-java-21:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-java-test:processResources UP-TO-DATE
> Task :rewrite-java:processResources UP-TO-DATE
> Task :rewrite-groovy:processResources UP-TO-DATE
> Task :rewrite-java-test:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-groovy:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-java:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-java-21:writeManifestProperties
> Task :rewrite-java-test:writeManifestProperties
> Task :rewrite-groovy:writeManifestProperties
> Task :rewrite-java:writeManifestProperties
> Task :rewrite-kotlin:processResources UP-TO-DATE
> Task :rewrite-groovy:processTestResources UP-TO-DATE
> Task :rewrite-test:processResources UP-TO-DATE
> Task :rewrite-kotlin:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-test:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-kotlin:writeManifestProperties
> Task :rewrite-test:writeManifestProperties
> Task :rewrite-java-lombok:unpackAndRenameLombok UP-TO-DATE
> Task :rewrite-java-lombok:processResources UP-TO-DATE
> Task :rewrite-java-lombok:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-java-lombok:writeManifestProperties
> Task :rewrite-core:compileJava UP-TO-DATE
> Task :rewrite-core:processResources UP-TO-DATE
> Task :rewrite-core:classes UP-TO-DATE
> Task :rewrite-core:createPropertiesFileForJar UP-TO-DATE
> Task :rewrite-core:writeManifestProperties
> Task :rewrite-java-lombok:compileJava UP-TO-DATE
> Task :rewrite-core:jar UP-TO-DATE
> Task :rewrite-java-lombok:classes UP-TO-DATE
> Task :rewrite-java-lombok:jar UP-TO-DATE
> Task :rewrite-test:compileJava UP-TO-DATE
> Task :rewrite-test:classes UP-TO-DATE
> Task :rewrite-test:jar UP-TO-DATE
> Task :rewrite-yaml:compileJava UP-TO-DATE
> Task :rewrite-java:compileJava UP-TO-DATE
> Task :rewrite-java:classes UP-TO-DATE
> Task :rewrite-java:shadowJar UP-TO-DATE
> Task :rewrite-kotlin:compileKotlin UP-TO-DATE
> Task :rewrite-kotlin:compileJava UP-TO-DATE
> Task :rewrite-kotlin:classes UP-TO-DATE
> Task :rewrite-kotlin:jar UP-TO-DATE
> Task :rewrite-java-21:compileJava UP-TO-DATE
> Task :rewrite-java-21:classes UP-TO-DATE
> Task :rewrite-java-21:jar UP-TO-DATE
> Task :rewrite-groovy:compileJava UP-TO-DATE
> Task :rewrite-groovy:classes UP-TO-DATE
> Task :rewrite-groovy:jar UP-TO-DATE
> Task :rewrite-java-test:compileJava UP-TO-DATE
> Task :rewrite-java-test:classes UP-TO-DATE
> Task :rewrite-java-test:jar UP-TO-DATE
> Task :rewrite-groovy:compileTestJava UP-TO-DATE
> Task :rewrite-groovy:testClasses UP-TO-DATE

Failed to parse sources or run recipe
java.lang.AssertionError: Failed to parse sources or run recipe
	at org.openrewrite.test.RewriteTest.lambda$defaultExecutionContext$14(RewriteTest.java:697)
	at org.openrewrite.test.RewriteTest$$Lambda/0x00007849c0184de8.accept(Unknown Source)
	at org.openrewrite.groovy.GroovyParser.lambda$parseInputs$3(GroovyParser.java:160)
	at org.openrewrite.groovy.GroovyParser$$Lambda/0x00007849c01cfbd0.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:301)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:135)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at org.openrewrite.groovy.GroovyParserTest.testMultilineStringInterpolation(GroovyParserTest.java:354)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x00007849c017c000.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00007849c00e0800.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.openrewrite.groovy.GroovyParsingException: Failed to parse file.groovy at cursor position 28. The surrounding characters in the original source are:
String name = """
    ${foo}~cursor~>
"""
	at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:223)
	at org.openrewrite.groovy.GroovyParser.lambda$parseInputs$3(GroovyParser.java:149)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Couldn't find delimiter: """ with fromIndex: 31
	at org.openrewrite.groovy.GroovyParserVisitor.sourceSubstring(GroovyParserVisitor.java:3108)
	at org.openrewrite.groovy.GroovyParserVisitor.access$1800(GroovyParserVisitor.java:81)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitGStringExpression(GroovyParserVisitor.java:1968)
	at org.codehaus.groovy.ast.expr.GStringExpression.visit(GStringExpression.java:53)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.doVisit(GroovyParserVisitor.java:822)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitDeclarationExpression(GroovyParserVisitor.java:1807)
	at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:117)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.lambda$visitExpressionStatement$11(GroovyParserVisitor.java:1847)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor$$Lambda/0x00007849c03089a0.get(Unknown Source)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.labeled(GroovyParserVisitor.java:878)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitExpressionStatement(GroovyParserVisitor.java:1846)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:41)
	at org.openrewrite.groovy.GroovyParserVisitor.convertTopLevelStatement(GroovyParserVisitor.java:2736)
	at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:209)
	... 20 more


Failed to parse file.groovy at cursor position 28. The surrounding characters in the original source are:
String name = """
    ${foo}~cursor~>
"""
org.openrewrite.groovy.GroovyParsingException: Failed to parse file.groovy at cursor position 28. The surrounding characters in the original source are:
String name = """
    ${foo}~cursor~>
"""
	at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:223)
	at org.openrewrite.groovy.GroovyParser.lambda$parseInputs$3(GroovyParser.java:149)
	at org.openrewrite.groovy.GroovyParser$$Lambda/0x00007849c01cfbd0.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:301)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:135)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at org.openrewrite.groovy.GroovyParserTest.testMultilineStringInterpolation(GroovyParserTest.java:354)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x00007849c017c000.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00007849c00e0800.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalArgumentException: Couldn't find delimiter: """ with fromIndex: 31
	at org.openrewrite.groovy.GroovyParserVisitor.sourceSubstring(GroovyParserVisitor.java:3108)
	at org.openrewrite.groovy.GroovyParserVisitor.access$1800(GroovyParserVisitor.java:81)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitGStringExpression(GroovyParserVisitor.java:1968)
	at org.codehaus.groovy.ast.expr.GStringExpression.visit(GStringExpression.java:53)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.doVisit(GroovyParserVisitor.java:822)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitDeclarationExpression(GroovyParserVisitor.java:1807)
	at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:117)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.lambda$visitExpressionStatement$11(GroovyParserVisitor.java:1847)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor$$Lambda/0x00007849c03089a0.get(Unknown Source)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.labeled(GroovyParserVisitor.java:878)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitExpressionStatement(GroovyParserVisitor.java:1846)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:41)
	at org.openrewrite.groovy.GroovyParserVisitor.convertTopLevelStatement(GroovyParserVisitor.java:2736)
	at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:209)
	... 20 more


Couldn't find delimiter: """ with fromIndex: 31
java.lang.IllegalArgumentException: Couldn't find delimiter: """ with fromIndex: 31
	at org.openrewrite.groovy.GroovyParserVisitor.sourceSubstring(GroovyParserVisitor.java:3108)
	at org.openrewrite.groovy.GroovyParserVisitor.access$1800(GroovyParserVisitor.java:81)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitGStringExpression(GroovyParserVisitor.java:1968)
	at org.codehaus.groovy.ast.expr.GStringExpression.visit(GStringExpression.java:53)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.doVisit(GroovyParserVisitor.java:822)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitDeclarationExpression(GroovyParserVisitor.java:1807)
	at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:117)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.lambda$visitExpressionStatement$11(GroovyParserVisitor.java:1847)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor$$Lambda/0x00007849c03089a0.get(Unknown Source)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.labeled(GroovyParserVisitor.java:878)
	at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitExpressionStatement(GroovyParserVisitor.java:1846)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:41)
	at org.openrewrite.groovy.GroovyParserVisitor.convertTopLevelStatement(GroovyParserVisitor.java:2736)
	at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:209)
	at org.openrewrite.groovy.GroovyParser.lambda$parseInputs$3(GroovyParser.java:149)
	at org.openrewrite.groovy.GroovyParser$$Lambda/0x00007849c01cfbd0.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:301)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:135)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at org.openrewrite.groovy.GroovyParserTest.testMultilineStringInterpolation(GroovyParserTest.java:354)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x00007849c017c000.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00007849c00e0800.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


> Task :rewrite-groovy:test FAILED
GroovyParserTest > testMultilineStringInterpolation() FAILED
    java.lang.AssertionError: Failed to parse sources or run recipe
        at org.openrewrite.test.RewriteTest.lambda$defaultExecutionContext$14(RewriteTest.java:697)
        at org.openrewrite.test.RewriteTest$$Lambda/0x00007849c0184de8.accept(Unknown Source)
        at org.openrewrite.groovy.GroovyParser.lambda$parseInputs$3(GroovyParser.java:160)
        at org.openrewrite.groovy.GroovyParser$$Lambda/0x00007849c01cfbd0.apply(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:301)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:135)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
        at org.openrewrite.groovy.GroovyParserTest.testMultilineStringInterpolation(GroovyParserTest.java:354)
        Caused by:
        org.openrewrite.groovy.GroovyParsingException: Failed to parse file.groovy at cursor position 28. The surrounding characters in the original source are:
        String name = """
            ${foo}~cursor~>
        """
            at app//org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:223)
            at app//org.openrewrite.groovy.GroovyParser.lambda$parseInputs$3(GroovyParser.java:149)
            ... 13 more
            Caused by:
            java.lang.IllegalArgumentException: Couldn't find delimiter: """ with fromIndex: 31
                at org.openrewrite.groovy.GroovyParserVisitor.sourceSubstring(GroovyParserVisitor.java:3108)
                at org.openrewrite.groovy.GroovyParserVisitor.access$1800(GroovyParserVisitor.java:81)
                at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitGStringExpression(GroovyParserVisitor.java:1968)
                at org.codehaus.groovy.ast.expr.GStringExpression.visit(GStringExpression.java:53)
                at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.doVisit(GroovyParserVisitor.java:822)
                at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitDeclarationExpression(GroovyParserVisitor.java:1807)
                at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
                at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:117)
                at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.lambda$visitExpressionStatement$11(GroovyParserVisitor.java:1847)
                at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor$$Lambda/0x00007849c03089a0.get(Unknown Source)
                at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.labeled(GroovyParserVisitor.java:878)
                at org.openrewrite.groovy.GroovyParserVisitor$RewriteGroovyVisitor.visitExpressionStatement(GroovyParserVisitor.java:1846)
                at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:41)
                at org.openrewrite.groovy.GroovyParserVisitor.convertTopLevelStatement(GroovyParserVisitor.java:2736)
                at org.openrewrite.groovy.GroovyParserVisitor.visit(GroovyParserVisitor.java:209)
                ... 14 more
1 test completed, 1 failed
[Incubating] Problems report is available at: file:///home/vladimirp/git/rewrite/build/reports/problems/problems-report.html
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':rewrite-groovy:test'.
> There were failing tests. See the report at: file:///home/vladimirp/git/rewrite/rewrite-groovy/build/reports/tests/test/index.html
Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/9.3.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 20s
45 actionable tasks: 9 executed, 36 up-to-date

```

### PR DESCRIPTION
**Pull request by vpa1977**
## What's changed?

Fix end delimiter search for multi-line groovy strings with interpolation.

## What's your motivation?

- Fixes: https://github.com/openrewrite/rewrite/issues/7429

## Anything in particular you'd like reviewers to focus on?

The test failed in the first place because the cursor moved to extract parts of the multi-line string. Maybe there is a better way? E.g. operate on the extracted value of the full multi-line string instead of the `source`?

## Have you considered any alternatives or workarounds?

The test failed in the first place because the cursor moved to extract parts of the multi-line string. Maybe there is a better way? E.g. operate on the extracted value of the full multi-line string instead of the `source`?
I tried to do a minimal change, but it feels slightly wrong, so maybe it would be good to do a bigger refactoring here.

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by vpa1977** [comment]
Note: unrelated CI failure:
```
Execution failed for task ':rewrite-gradle:test'.
> Could not resolve all files for configuration ':rewrite-gradle:testRuntimeClasspath'.
   > Could not resolve com.google.guava:guava:latest.release.
     Required by:
         project ':rewrite-gradle'
      > Could not resolve com.google.guava:guava:999.0.0-HEAD-android-SNAPSHOT.
         > Unable to load Maven meta-data from https://central.sonatype.com/repository/maven-snapshots/com/google/guava/guava/999.0.0-HEAD-android-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://central.sonatype.com/repository/maven-snapshots/com/google/guava/guava/999.0.0-HEAD-android-SNAPSHOT/maven-metadata.xml'. Received status code 500 from server: Server Error
```

**Comment by greg-at-moderne** [comment]
> Note: unrelated CI failure:

Correct. Went away on retry.

File: rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java [hunk 1]
```diff
@@ -1965,7 +1965,7 @@ public void visitGStringExpression(GStringExpression gstring) {
                     }
                 } else if (e instanceof ConstantExpression) {
                     // Get the string literal from the source, so escaping of newlines and the like works out of the box
-                    String value = sourceSubstring(cursor, delimiter.close);
+                    String value = sourceSubstring(cursor, delimiter.close, cursor + e.getText().length());
```
Comment (greg-at-moderne) [inline rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java]: Just thinking out loud. Instead of complicating the interface of the `sourceSubstring()` method...
... couldn't we just call here with slightly different arguments, i.e.
```
sourceSubstring(cursor + e.getText().length(), delimiter.close)
```
or would it not work?

Comment (vpa1977) [reply rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java]: Unfortunately it wont. 

The error condtion is ``<character>"""`` so calling `sourceSubstring(cursor + e.getText().length(), delimiter.close)` will place beginIndex at `"""` but then the existing logic that calculates `max` will move the start index right after it. 

If we remove the +1 / `untilDelim.length() ` then we arrive at the infinite loop bug that the previous commit[1] tried to fix. 

I do not like my solution either, I wonder if it would be better if:
 - we detect that we have string interpolation at line 1975. 
 - Extract a new method that handles groovy strings with interpolation
 - This new method consumes *only* extracted string. This way we do not need to run delimiter search and risk further bugs. 

[1] https://github.com/openrewrite/rewrite/commit/b9b79151be7f8d5f0806c3d75161e4bdbf460e69

Comment (greg-at-moderne) [reply rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java]: OK. Tried your suggestion in 115f956040d840233073d91d5ffed3faf710e4be. I hope this is what you suggested (?)

Comment (vpa1977) [reply rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java]: Yes, thank you!

The only thing I do not really understand, which is semi-related:  why sourceSubstring uses delimiter.close as the parameter? Should not we use delimiter.begin since we are skipping cursor + delimiter? But it probably does not matter as delimiter.begin length is always greater than delimiter.close length.

Comment (greg-at-moderne) [reply rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java]: > Should not we use delimiter.begin 

I might be missing something, but `delimiter.open` is already skipped at https://github.com/vpa1977/rewrite/blob/115f956040d840233073d91d5ffed3faf710e4be/rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java#L1937

Comment (vpa1977) [reply rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java]: > > Should not we use delimiter.begin
> 
> I might be missing something, but `delimiter.open` is already skipped at https://github.com/vpa1977/rewrite/blob/115f956040d840233073d91d5ffed3faf710e4be/rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java#L1937

The bit that got me confused is the actual implementation of `sourceSubstring` https://github.com/vpa1977/rewrite/blob/115f956040d840233073d91d5ffed3faf710e4be/rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java#L3099 - it starts at the cursor position (beginIndex) and then tries to skip the closing delimiter to find substring to the next closing delimiter.

Comment (vpa1977) [reply rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java]: @greg-at-moderne I apologise for the ping, would it be possible to looking into merging this PR or a similar solution, as the bug prevents refactoring of Gradle Groovy DSL.

**Comment by greg-at-moderne** [comment]
Thanks again, @vpa1977 for your valuable contribution!

**Comment by vpa1977** [comment]
> Thanks again, @vpa1977 for your valuable contribution!

Thank you =) You did all the heavy lifting here, I just found this bug.
