### PR TITLE
Handle the `instanceof final` pattern matching syntax in Java

### LINKED ISSUE #5200: Java idempotency issue with `instanceof final` pattern matching
## What version of OpenRewrite are you using?

Current main = 45ca3c98d074f7434f8d4aec781228619b21313d

## What is the smallest, simplest way to reproduce the problem?

```java
    @Test
    void instanceofFinal() {
        rewriteRun(
          java(
            """
            public class Main {
              public static void main(String[] argv) {
                String s = "a";
                if (s instanceof final String s2) {
                    System.out.println(s2);
                }
              }
            }
            """
          )
        );
    }
```

## What did you expect to see?

No change.

## What did you see instead?

```diff
-       if (s instanceof final String s2) {
+       if (s instanceof StringString s2) {
```

## Context

Inspired by real-life: https://github.com/PaperMC/Velocity/blob/d9f1016bd57d50f5052bb90222894adb40fd256c/api/src/main/java/com/velocitypowered/api/proxy/server/PingOptions.java#L84

### PR DESCRIPTION
**Pull request by sudouser777**
1. Updated the Java 17 and 21 Parser to handle `final` modifier in `instance of` patternmatching.
2. Added new field `modifier` to `J.InstanceOf` class.
3. Updated the `JavaPrinter`  to handle new `modifier` field.

- closes #5200 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by sudouser777** [comment]
closes #5200

File: rewrite-java/src/main/java/org/openrewrite/java/tree/J.java [hunk 1]
```diff
@@ -2986,6 +2986,11 @@ public InstanceOf withExpression(Expression expression) {
         @Getter
         JavaType type;
 
+        @With
+        @Nullable
+        @Getter
+        Modifier modifier;
+
```
Comment (greg-at-moderne) [inline rewrite-java/src/main/java/org/openrewrite/java/tree/J.java:2993]: I think for backward compatibility reasons we would need another constructor which has the old signature. So that recipes code which uses the constructor continues to compile - without and with this change.

One example of such backward incompatible change is what you have noticed yourself in `rewrite-groovy`. But the problem might also affect other pieces of code, outside of this repository.

You can mark the "new old" constructor as deprecated already.

Comment (sudouser777) [reply rewrite-java/src/main/java/org/openrewrite/java/tree/J.java:2993]: I made the change. Thank you for the suggestion.

Comment (greg-at-moderne) [reply rewrite-java/src/main/java/org/openrewrite/java/tree/J.java:2993]: b9d44fa78f2deab60a96319011616e20c59399b2

**Review by greg-at-moderne — APPROVED** [review]
LGTM.
Thanks for this valuable contribution.

**Review by timtebeek — APPROVED** [review]
Great to see you immediately jump to a detailed contribution here @sudouser777 ! Thanks a lot!
