### PR TITLE
Handling null source in MergeYaml

### LINKED ISSUE #4955: NPE in MergeYaml
## What is the smallest, simplest way to reproduce the problem?

Configure the `org.openrewrite.yaml.MergeYaml` without any of the required parameters (I just copied a list of recipes taken from the discover goal) and run OpenRewrite.

## What is the full stack trace of any errors you encountered?

```
 java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "source" is null
	at org.openrewrite.Parser$Input.lambda$fromString$0(Parser.java:175)
	at org.openrewrite.Parser$Input.getSource(Parser.java:215)
	at org.openrewrite.tree.ParseError.build(ParseError.java:97)
	at org.openrewrite.yaml.YamlParser.lambda$parseInputs$0(YamlParser.java:77)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.openrewrite.yaml.MergeYaml.lambda$validate$1(MergeYaml.java:66)
	at org.openrewrite.Validated.test(Validated.java:81)
	at org.openrewrite.yaml.MergeYaml.validate(MergeYaml.java:64)
	at org.openrewrite.Recipe.validate(Recipe.java:383)
```

### PR DESCRIPTION
**Pull request by greg-at-moderne**
## What's changed?

Slight change in how invalid input (null source) is handled by `MergeYaml`.
Now returning a proper validation error instead of `NullPointerException`.

## What's your motivation?
- fixes #4955

### CODE REVIEW

**Review by jevanlingen — APPROVED** [review]

**Comment by jevanlingen** [comment]
Though I agree with this fix, I find it actually a little bit weird. The `yaml` property is defined as non-null. Should we really still create fixes to protect it against misuse?

**Comment by greg-at-moderne** [comment]
I think it's just a tiny improvement on the user experience. A more meaningful error message likely.

File: rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java [hunk 1]
```diff
@@ -121,6 +121,9 @@ public Validated<Object> validate() {
         return super.validate()
                 .and(Validated.test("yaml", "Must be valid YAML",
```
Comment (jevanlingen) [inline rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java:122]:
```suggestion
                .and(Validated.required("key", key))
                .and(Validated.test("yaml", "Must be valid YAML",
```

I we want to go down this road, add this as well 😉
