### PR TITLE
Fix bug in `TabsAndIndentsVisitor`

### LINKED ISSUE #2722: `RemoveUnusedImports` can mess up indentation when source has header
When a Java source has a header and the `RemoveUnusedImports` recipe removes all headers, it messes up the source indentation.

```java
    @Test
    void removeAllImportsWithHeader() {
        rewriteRun(
          java(
            """
              /*
               * header
               */
              package x;
              import java.util.List;
              class A {}
              """,
            """
              /*
               * header
               */
              package x;

              class A {}
              """
          )
        );
    }
```

The actual source looks like this (the 8 spaces indentation should not be part of the source):
```java
        /*
         * header
         */
        package x;

        class A {}
```

### PR DESCRIPTION
**Pull request by knutwannheden**
A problem with the logic in `TabsAndIndentsVisitor` which was observed with the `RemoveUnusedImports` recipe could lead to the whole or at least the beginning of compilation units with a copyright header getting indented. This problem may also affect other recipes using the `JavaVisitor#autoFormat()` method.

Fixes #2722

### CODE REVIEW

File: rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java [hunk 1]
```diff
@@ -69,7 +69,9 @@ public J visit(@Nullable Tree tree, P p, Cursor parent) {
         }
         Iterator<Object> itr = parent.getPath(J.class::isInstance);
         J next = (itr.hasNext()) ? (J) itr.next() : null;
-        preVisit(next, p);
+//        if (next != null) {
+            preVisit(next, p);
+//        }
```
Comment (sambsnyd) [inline rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java:74]:
```suggestion
        preVisit(next, p);
```

File: rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java [hunk 2]
```diff
@@ -69,7 +69,9 @@ public J visit(@Nullable Tree tree, P p, Cursor parent) {
         }
         Iterator<Object> itr = parent.getPath(J.class::isInstance);
         J next = (itr.hasNext()) ? (J) itr.next() : null;
-        preVisit(next, p);
+        if (next != null) {
+            preVisit(next, p);
+        }
```
Comment (sambsnyd) [inline rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java:74]:
```suggestion
        preVisit(next, p);
```

File: rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java (hunk 1 above)
Comment (knutwannheden) [reply rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java]: @sambsnyd Thanks for spotting. The commented out lines should actually have been the fix. While testing a few more cases I temporarily reverted the fix and in the end accidentally committed it that way...

**Comment by knutwannheden** [comment]
I think I have seen this indenting in the public SaaS a few times before. I hope this will fix it.
